import assert from 'node:assert/strict'
import { JSDOM } from 'jsdom'
import { createServer } from 'vite'
import React, { act, useEffect } from 'react'
import { MemoryRouter, useLocation, useNavigate } from 'react-router-dom'

const dom = new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>', { url: 'http://localhost/' })
for (const key of ['window', 'document', 'navigator', 'HTMLElement', 'HTMLInputElement', 'localStorage', 'FormData']) Object.defineProperty(globalThis, key, { configurable: true, value: dom.window[key] })
const { createRoot } = await import('react-dom/client')
const errors = []
dom.window.addEventListener('error', (event) => errors.push(event.error))
globalThis.IS_REACT_ACT_ENVIRONMENT = true
dom.window.HTMLDialogElement.prototype.showModal = function () { this.open = true }
dom.window.HTMLElement.prototype.setPointerCapture = () => {}
let frameId = 0, frames = new Map(), audioTime = 0, scheduledVoices = 0, route, navigate
const requestFrame = (callback) => { frames.set(++frameId, callback); return frameId }
const cancelFrame = (id) => frames.delete(id)
globalThis.requestAnimationFrame = dom.window.requestAnimationFrame = requestFrame
globalThis.cancelAnimationFrame = dom.window.cancelAnimationFrame = cancelFrame
const server = await createServer({ server: { middlewareMode: true }, appType: 'custom', logLevel: 'error' })
let root
const audio = { start: async () => {}, stop() {}, stopChannel() {}, dispose() {}, setVolume() {}, setChannelVolume() {}, play: async () => {}, clock: () => audioTime, schedule() { scheduledVoices++ } }
const engineFactory = () => audio
function Probe() { const location = useLocation(); const go = useNavigate(); useEffect(() => { route = location.pathname; navigate = go }, [location.pathname, go]); return null }
const h = React.createElement
async function pump() { await act(async () => { const pending = [...frames.values()]; frames.clear(); for (const fn of pending) fn(0) }) }
async function click(element) { assert.ok(element, 'Click target exists'); await act(async () => element.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }))) }
async function choose(element, value) { assert.ok(element, 'Select exists'); await act(async () => { element.value = String(value); element.dispatchEvent(new dom.window.Event('change', { bubbles: true })) }) }
const button = (text) => [...document.querySelectorAll('button')].find((el) => el.textContent.trim() === text)
const select = (label) => [...document.querySelectorAll('label')].find((el) => el.textContent.startsWith(label))?.querySelector('select')
async function mount(App, path) {
  if (root) await act(async () => root.unmount())
  root = createRoot(document.getElementById('root'))
  await act(async () => root.render(h(MemoryRouter, { initialEntries: [path] }, h(Probe), h(App, { engineFactory }))))
  await pump()
}

try {
  const { default: App } = await server.ssrLoadModule('/src/App.jsx')
  await mount(App, '/')
  assert.match(document.body.textContent, /Your sound/)
  await click(button('Create a lobby'))
  const nameInput = document.querySelector('input')
  await act(async () => {
    Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype, 'value').set.call(nameInput, 'Alex')
    nameInput.dispatchEvent(new dom.window.Event('input', { bubbles: true }))
    nameInput.dispatchEvent(new dom.window.Event('change', { bubbles: true }))
  })
  await act(async () => document.querySelector('form').dispatchEvent(new dom.window.Event('submit', { bubbles: true, cancelable: true })))
  await pump()
  assert.match(route, /^\/lobby\/[A-Z2-9]{6}$/)
  const lobbyPath = route
  const code = route.split('/')[2]
  await choose(select('Key'), 11)
  await choose(select('Mood / scale'), 'minor')
  await choose(select('Turn length'), 300)
  await choose(select('Listen between turns'), 15)
  const stored = JSON.parse(localStorage.getItem(`pass-the-beat:room:${code}`))
  assert.equal(stored.players[0].name, 'Alex')
  assert.equal(stored.turnSeconds, 300)
  assert.equal(stored.listenSeconds, 15)
  await click(button('Start session')); await pump()
  assert.match(document.body.textContent, /Choose your difficulty/)
  await click([...document.querySelectorAll('.difficulty-option')].find((option) => option.textContent.includes('Standard Mode'))); await pump()
  assert.equal(route, `/studio/${code}`)
  assert.equal(document.querySelectorAll('.track-card').length, 6)
  assert.match(document.querySelector('.queue-footer').textContent, /5:00/)
  await choose(select('Snap'), 0.125)
  const grid = document.querySelector('.note-grid')
  grid.getBoundingClientRect = () => ({ left: 0, top: 0, width: 800, height: 425 })
  await act(async () => grid.dispatchEvent(new dom.window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 100, clientY: 205 })))
  assert.equal(document.querySelectorAll('.piano-note').length, 1)
  assert.match(document.querySelector('.piano-note').getAttribute('aria-label'), /length 0.125/)
  await act(async () => {
    const note = document.querySelector('.piano-note')
    note.dispatchEvent(new dom.window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 100, clientY: 205 }))
    note.dispatchEvent(new dom.window.MouseEvent('pointermove', { bubbles: true, clientX: 125, clientY: 205 }))
    note.dispatchEvent(new dom.window.MouseEvent('pointerup', { bubbles: true }))
  })
  assert.match(document.querySelector('.piano-note').getAttribute('aria-label'), /position 3.5/)
  await act(async () => {
    const handle = document.querySelector('.note-resize')
    handle.dispatchEvent(new dom.window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 130, clientY: 205 }))
    handle.dispatchEvent(new dom.window.MouseEvent('pointermove', { bubbles: true, clientX: 180, clientY: 205 }))
    handle.dispatchEvent(new dom.window.MouseEvent('pointerup', { bubbles: true }))
  })
  assert.match(document.querySelector('.piano-note').getAttribute('aria-label'), /length 1.125/)
  await act(async () => {
    const handle = document.querySelector('.note-resize')
    handle.dispatchEvent(new dom.window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 180, clientY: 205 }))
    handle.dispatchEvent(new dom.window.MouseEvent('pointermove', { bubbles: true, clientX: 130, clientY: 205 }))
    handle.dispatchEvent(new dom.window.MouseEvent('pointerup', { bubbles: true }))
  })
  assert.match(document.querySelector('.piano-note').getAttribute('aria-label'), /length 0.125/)
  assert.equal(document.querySelectorAll('.ghost-note').length, 0)
  assert.match(document.querySelector('.guide-caption').textContent, /B minor/)
  assert.ok(document.querySelectorAll('.pitch-band.in-scale').length > 0)
  await click(document.querySelector('.polyphony-toggle input'))
  assert.equal(document.querySelector('.polyphony-toggle input').checked, true)
  await act(async () => {
    grid.dispatchEvent(new dom.window.MouseEvent('pointerdown', { bubbles: true, button: 0, ctrlKey: true, clientX: 120, clientY: 200 }))
    grid.dispatchEvent(new dom.window.MouseEvent('pointermove', { bubbles: true, clientX: 150, clientY: 230 }))
    grid.dispatchEvent(new dom.window.MouseEvent('pointerup', { bubbles: true }))
  })
  assert.equal(document.querySelectorAll('.piano-note.selected').length, 1)
  assert.equal(document.querySelector('.selection-box'), null)
  await click(button('Select all'))
  await click(button('Duplicate'))
  assert.equal(document.querySelectorAll('.piano-note').length, 2)
  await click(document.querySelector('.editor-tools .mode-switch button'))
  assert.equal(document.querySelectorAll('.drum-sequencer .step-buttons > button').length, 32)
  await click(button('Every 2 steps'))
  assert.equal(document.querySelectorAll('.drum-sequencer .step-buttons > button.on').length, 16)
  await click(document.querySelector('[aria-label="Undo"]'))
  await click(document.querySelector('.drum-sequencer .step-buttons > button'))
  assert.equal(document.querySelector('.drum-sequencer .step-buttons > button').getAttribute('aria-pressed'), 'true')
  await click([...document.querySelectorAll('.editor-tools .mode-switch button')][1])
  assert.equal(document.querySelectorAll('.piano-note').length, 3, 'Mode switching preserves notes')
  await click(button('Select all'))
  await act(async () => document.querySelector('.note-grid').dispatchEvent(new dom.window.KeyboardEvent('keydown', { bubbles: true, ctrlKey: true, code: 'KeyC', key: 'c' })))
  await act(async () => document.querySelector('.note-grid').dispatchEvent(new dom.window.KeyboardEvent('keydown', { bubbles: true, ctrlKey: true, code: 'KeyV', key: 'v' })))
  assert.equal(document.querySelectorAll('.piano-note').length, 6)
  assert.equal(document.querySelectorAll('.piano-note.selected').length, 3)
  const copiedPositions = [...document.querySelectorAll('.piano-note.selected')].map((note) => parseFloat(note.style.left))
  document.querySelector('.note-grid').getBoundingClientRect = () => ({ left: 0, top: 0, width: 800, height: 425 })
  await act(async () => {
    const note = document.querySelector('.piano-note.selected')
    note.dispatchEvent(new dom.window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 100, clientY: 205 }))
    note.dispatchEvent(new dom.window.MouseEvent('pointermove', { bubbles: true, clientX: 150, clientY: 205 }))
    note.dispatchEvent(new dom.window.MouseEvent('pointerup', { bubbles: true }))
  })
  assert.deepEqual([...document.querySelectorAll('.piano-note.selected')].map((note) => parseFloat(note.style.left)), copiedPositions.map((left) => left + 6.25))
  await click(button('Delete selected'))
  assert.equal(document.querySelectorAll('.piano-note').length, 3)
  // Browser shortcuts must work while a sequencer button or the page has focus.
  await click(button('Select all'))
  const duplicateKey = new dom.window.KeyboardEvent('keydown', { bubbles: true, cancelable: true, ctrlKey: true, code: 'KeyD', key: 'в' })
  await act(async () => document.body.dispatchEvent(duplicateKey))
  assert.equal(duplicateKey.defaultPrevented, true)
  assert.equal(document.querySelectorAll('.piano-note').length, 6)
  await click(button('Delete selected'))
  const pianoMenu = new dom.window.MouseEvent('contextmenu', { bubbles: true, cancelable: true })
  await act(async () => document.querySelector('.note-grid').dispatchEvent(pianoMenu))
  assert.equal(pianoMenu.defaultPrevented, true)
  await act(async () => document.querySelector('.piano-note').dispatchEvent(new dom.window.MouseEvent('pointerdown', { bubbles: true, button: 2, buttons: 2 })))
  await act(async () => document.querySelector('.piano-note').dispatchEvent(new dom.window.MouseEvent('pointermove', { bubbles: true, buttons: 2 })))
  await act(async () => window.dispatchEvent(new dom.window.MouseEvent('pointerup', { button: 2 })))
  assert.equal(document.querySelectorAll('.piano-note').length, 1)
  await click(document.querySelector('[aria-label="Undo"]'))
  await click(document.querySelector('[aria-label="Undo"]'))
  await click(document.querySelector('.editor-tools .mode-switch button'))
  const step = document.querySelector('.drum-sequencer .step-buttons > button')
  const wasOn = step.getAttribute('aria-pressed')
  for (let i = 0; i < 2; i++) {
    const space = new dom.window.KeyboardEvent('keydown', { bubbles: true, cancelable: true, code: 'Space', key: ' ' })
    await act(async () => step.dispatchEvent(space))
    assert.equal(space.defaultPrevented, true)
    assert.equal(document.querySelector('.transport-play').classList.contains('active'), i === 0)
    assert.equal(step.getAttribute('aria-pressed'), wasOn)
  }
  await click(document.querySelector('[aria-label="Stop"]'))
  await click(button('Every 2 steps'))
  await act(async () => document.querySelectorAll('.drum-sequencer .step-buttons > button')[0].dispatchEvent(new dom.window.MouseEvent('pointerdown', { bubbles: true, button: 2, buttons: 2 })))
  await act(async () => document.querySelectorAll('.drum-sequencer .step-buttons > button')[2].dispatchEvent(new dom.window.MouseEvent('pointermove', { bubbles: true, buttons: 2 })))
  await act(async () => window.dispatchEvent(new dom.window.MouseEvent('pointerup', { button: 2 })))
  assert.equal(document.querySelectorAll('.drum-sequencer .step-buttons > button.on').length, 14)
  const stepMenu = new dom.window.MouseEvent('contextmenu', { bubbles: true, cancelable: true })
  await act(async () => document.querySelector('.step-buttons').dispatchEvent(stepMenu))
  assert.equal(stepMenu.defaultPrevented, true)
  for (let i = 0; i < 3; i++) await click(document.querySelector('[aria-label="Undo"]'))
  await click([...document.querySelectorAll('.editor-tools .mode-switch button')][1])
  await act(async () => navigate(-1)); await pump()
  assert.equal(route, lobbyPath)
  assert.ok(button('Resume session'))
  assert.ok(document.querySelector('fieldset').disabled)
  await click(button('Resume session')); await pump()
  assert.equal(document.querySelectorAll('.piano-note').length, 3)
  await click(button('Pass the beat')); await pump()
  assert.match(document.querySelector('.listen-banner').textContent, /15s/)
  assert.ok(document.querySelector('.transport-play').disabled)
  audioTime = 7.58; await pump()
  assert.match(document.querySelector('.listen-banner').textContent, /8s/)
  audioTime = 15.09; await pump(); await pump()
  assert.equal(document.querySelector('.listen-banner'), null)
  assert.ok(!document.querySelector('.transport-play').disabled)
  assert.equal(document.querySelectorAll('.track-card.locked').length, 0)
  assert.equal(document.querySelector('[aria-label="BPM"]').disabled, false)
  await click(document.querySelector('[aria-label="Clear track"]'))
  assert.equal(document.querySelectorAll('.piano-note').length, 0, 'Next player can erase previous player notes')
  await click(button('Finish session')); await pump(); await pump()
  assert.equal(route, `/result/${code}`)
  assert.match(document.body.textContent, /You made this/)
  await click(button('Play again')); await pump()
  assert.equal(route, lobbyPath)
  assert.equal(select('Turn length').value, '300')
  await mount(App, lobbyPath)
  assert.equal(select('Listen between turns').value, '15', 'Lobby settings survive reload')
  await mount(App, `/studio/${code}`)
  assert.equal(route, lobbyPath, 'Reloaded editor returns safely to lobby')
  await mount(App, '/lobby/INVALID')
  assert.equal(route, '/')
  const beginnerRoom = JSON.parse(localStorage.getItem(`pass-the-beat:room:${code}`))
  beginnerRoom.turnSeconds = 60
  beginnerRoom.turnSecondsCustom = false
  localStorage.setItem(`pass-the-beat:room:${code}`, JSON.stringify(beginnerRoom))
  await mount(App, lobbyPath)
  await click(button('Start session')); await pump()
  await click([...document.querySelectorAll('.difficulty-option')].find((option) => option.textContent.includes('Beginner Mode'))); await pump()
  assert.match(document.querySelector('.beginner-mode-badge').textContent, /BEGINNER MODE/)
  assert.match(document.querySelector('.beginner-mode-banner').textContent, /Build with the grid or add a ready-made segment/)
  assert.equal(document.querySelectorAll('.beginner-category-list button').length, 7)
  assert.ok(document.querySelector('.beginner-add-instrument-toggle'))
  assert.equal(document.querySelectorAll('.beginner-channel-item').length, 6)
  assert.equal(document.querySelector('.knob-control'), null)
  assert.equal(document.querySelector('[aria-label^="Configure "]'), null)
  assert.match(document.querySelector('.beginner-turn-prompt').textContent, /Alex: Add your melodic loop above the beat!/)
  assert.equal(document.querySelector('.turn-seconds').textContent, '2:00')
  const starterToggle = document.querySelector('.starter-beat-control input')
  assert.equal(starterToggle.checked, true, 'Starter rhythm is enabled by default')
  const soloKick = document.querySelector('[aria-label="Solo Kick"]')
  const muteKick = document.querySelector('[aria-label="Mute Kick"]')
  assert.ok(soloKick && muteKick, 'Mute and solo controls are available in channel headers')
  await click(soloKick); await pump()
  assert.equal(soloKick.getAttribute('aria-pressed'), 'true')
  await click(muteKick); await pump()
  assert.equal(soloKick.getAttribute('aria-pressed'), 'true', 'Mute and solo are independent toggles')
  await click(document.querySelector('[aria-label="Unmute Kick"]')); await pump()
  audioTime = 0
  await click(document.querySelector('.transport-play')); await pump()
  assert.ok([...document.querySelectorAll('.beginner-channel-item')].find((item) => item.textContent.includes('Kick')).classList.contains('sound-active'), 'A kick onset pulses its channel header')
  await click(document.querySelector('[aria-label="Stop"]')); await pump()
  await click(document.querySelector('[aria-label="Unsolo Kick"]')); await pump()
  await click(starterToggle); await pump()
  assert.equal(starterToggle.checked, false)
  assert.match(document.querySelector('.starter-beat-control').textContent, /Off/)
  await click(starterToggle); await pump()
  assert.equal(starterToggle.checked, true, 'Starter rhythm can be restored during the turn')
  assert.deepEqual([...document.querySelectorAll('.beginner-category-list button strong')].map((button) => button.textContent), ['PIANO & KEYS', 'SYNTHS & LEADS', 'BASSLINES', 'STRINGS & PADS', 'DRUM BEATS', 'BRASS & HORNS', 'VOCAL FX'])
  assert.equal(document.querySelectorAll('.melody-pattern-card').length, 8)
  assert.ok(document.querySelector('.piano-editor'), 'Beginner keeps the interactive piano roll visible')
  const pianoGrid = document.querySelector('.note-grid')
  pianoGrid.getBoundingClientRect = () => ({ left: 0, top: 0, width: 800, height: 425 })
  await act(async () => pianoGrid.dispatchEvent(new dom.window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 50, clientY: 119 })))
  assert.match(document.querySelector('.piano-note').getAttribute('aria-label'), /^E5,/, 'Manual off-scale notes snap to C major pentatonic')
  assert.match(pianoGrid.getAttribute('aria-label'), /C major pentatonic/)
  const firstCard = document.querySelector('.melody-pattern-card')
  assert.match(firstCard.querySelector('h5').textContent, /Piano — Classic Ballad/)
  assert.ok(firstCard.querySelector('.melody-vibe-tag').textContent)
  assert.ok(firstCard.textContent.includes('Classic Ballad'))
  assert.match(firstCard.querySelector('.preview-pattern-button').textContent, /Preview/)
  assert.match(firstCard.querySelector('.button.primary').textContent, /Add to Track/)
  const previousScheduledVoices = scheduledVoices
  for (const categoryName of ['BRASS & HORNS', 'VOCAL FX']) {
    await click([...document.querySelectorAll('.beginner-category-list button')].find((item) => item.textContent.includes(categoryName))); await pump()
    assert.equal(document.querySelectorAll('.melody-pattern-card').length, 8)
  }
  await click([...document.querySelectorAll('.beginner-category-list button')].find((item) => item.textContent.includes('DRUM BEATS'))); await pump()
  assert.equal(document.querySelectorAll('.melody-pattern-card').length, 8)
  assert.equal(document.querySelector('.melody-pattern-card h5').textContent.includes('Piano'), false, 'The right panel filters to the chosen category')
  await click(document.querySelector('.melody-pattern-card .preview-pattern-button'))
  assert.ok(scheduledVoices - previousScheduledVoices > 8, 'Drum preview schedules the multi-instrument groove')
  const drumCard = [...document.querySelectorAll('.melody-pattern-card')].find((card) => card.textContent.includes('Lo-Fi Chill Beat'))
  await click(drumCard.querySelector('.button.primary')); await pump()
  assert.match(drumCard.textContent, /Selected/)
  assert.equal(document.querySelectorAll('.beginner-channel-item').length, 9, 'Drum segment adds three active channels')
  assert.equal(document.querySelector('.listen-banner'), null, 'Adding a sequence does not finish the turn')
  await click([...document.querySelectorAll('.beginner-category-list button')].find((item) => item.textContent.includes('BASSLINES'))); await pump()
  const bassCard = [...document.querySelectorAll('.melody-pattern-card')].find((card) => card.textContent.includes('Deep Sub Pulse'))
  await click(bassCard.querySelector('.button.primary')); await pump()
  await click([...document.querySelectorAll('.beginner-category-list button')].find((item) => item.textContent.includes('PIANO & KEYS'))); await pump()
  const balladCard = [...document.querySelectorAll('.melody-pattern-card')].find((card) => card.textContent.includes('Classic Ballad'))
  await click(balladCard.querySelector('.button.primary')); await pump()
  assert.equal(document.querySelectorAll('.beginner-channel-item').length, 11)
  assert.match(document.querySelector('.queue-heading').textContent, /Creating now: Alex/)
  const [minutes, seconds] = document.querySelector('.turn-seconds').textContent.split(':').map(Number)
  assert.ok(minutes * 60 + seconds > 100, 'Adding and removing loops preserves the two-minute timer')
  assert.match(document.querySelector('.preset-success-toast').textContent, /Classic Ballad added to the shared song/)
  await click(document.querySelector('[aria-label="Remove Lo-Fi Chill Beat"]')); await pump()
  assert.equal(document.querySelectorAll('.beginner-channel-item').length, 8, 'Removing the drum segment removes all its channels')
  assert.equal(document.querySelector('.listen-banner'), null)
  await click(button('Pass the beat')); await pump()
  assert.match(document.querySelector('.listen-banner').textContent, /Player 2, listen/, 'Manual pass advances to the next player')
  const tracksAfterPass = document.querySelectorAll('.beginner-channel-item').length
  await act(async () => window.dispatchEvent(new dom.window.KeyboardEvent('keydown', { bubbles: true, cancelable: true, ctrlKey: true, code: 'KeyZ', key: 'z' })))
  assert.equal(document.querySelectorAll('.beginner-channel-item').length, tracksAfterPass, 'Undo cannot change saved tracks during another player turn')
  assert.doesNotMatch(document.body.textContent, /[А-Яа-яЁё]/)
  assert.deepEqual(errors, [], 'No DOM or React event errors')
  console.log('UI checks passed: difficulty selection, beginner pitch lock and simplified controls, standard editing, routing, lobby settings, playback, timed turns and results.')
} finally {
  if (root) await act(async () => root.unmount())
  await server.close()
  dom.window.close()
}
